# Generated by Django 5.1.6 on 2026-08-31 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('contrato_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('modalidad', models.CharField(blank=True, max_length=255, null=True)),
                ('ronda', models.CharField(blank=True, max_length=100, null=True)),
                ('licitacion', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('pozos_comprometidos', models.IntegerField(blank=True, null=True)),
                ('pozos_terminados', models.IntegerField(blank=True, null=True)),
                ('operador_principal', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_licitante', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_yacimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('superficie_km2', models.FloatField(blank=True, null=True)),
                ('fecha_firma', models.CharField(blank=True, max_length=50, null=True)),
                ('duracion_anios', models.FloatField(blank=True, null=True)),
                ('vence', models.CharField(blank=True, max_length=50, null=True)),
                ('estatus', models.CharField(blank=True, max_length=100, null=True)),
                ('participacion_estado', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id_socio', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('empresa_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_participacion', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_participacion', models.FloatField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratistas', to='contratos.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='DatoGeologico',
            fields=[
                ('id_datgeo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('provincia_petrolera', models.CharField(blank=True, max_length=255, null=True)),
                ('provincia_geologica', models.CharField(blank=True, max_length=255, null=True)),
                ('superficie', models.CharField(blank=True, max_length=255, null=True)),
                ('cobertura', models.CharField(blank=True, max_length=255, null=True)),
                ('edad_play', models.CharField(blank=True, max_length=255, null=True)),
                ('litologias', models.TextField(blank=True, null=True)),
                ('hidrocarburo', models.CharField(blank=True, max_length=255, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geologicos', to='contratos.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='InversionEjercida',
            fields=[
                ('id_inversion', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_ejercido_usd', models.FloatField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversiones', to='contratos.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='LineaTiempo',
            fields=[
                ('id_timeline', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.CharField(blank=True, max_length=100, null=True)),
                ('evento', models.TextField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_tiempo', to='contratos.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='PmtResumen',
            fields=[
                ('id_pmt', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('programa_minimo', models.FloatField(blank=True, null=True)),
                ('incremento', models.FloatField(blank=True, null=True)),
                ('periodo_adicional', models.FloatField(blank=True, null=True)),
                ('total_requerido', models.FloatField(blank=True, null=True)),
                ('acreditadas', models.FloatField(blank=True, null=True)),
                ('fecha_limite', models.CharField(blank=True, max_length=50, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmt', to='contratos.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_punto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('numero_vertice', models.IntegerField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='contratos.contrato')),
            ],
        ),
    ]
